{# jinja2 #}
#cloud-config
# for PT DevOps Testing
# objective: install stack of nginx+flask+redis
output:
 all: "|tee -a /var/tmp/cloudinit.out"
hostname: {{ hostname }}
bootcmd:
 - useradd -g 1000 -u 1001 -s /bin/bash -d /home/pt-user -c 'AWS default user (PT)' pt-user
 - usermod -g wheel pt-user
apt_sources:
packages:
 - redis
 - python-pip
 - python-boto
 - python-flask
 - nginx
final_message: "The system is up, after $UPTIME seconds"
runcmd:
{% if production %}
 - touch /PRODUCTION
{% else %}
 - touch /DEVEL
{% endif %}
 - echo [Credentials] > /etc/default/boto
 - echo aws_access_key_id = {{ aws_key }} >> /etc/default/boto
 - echo aws_secret_access_key = {{ aws_secret }} >> /etc/default/boto
 - echo [s3] >> /etc/default/boto
 - echo host = s3.us-west-2.amazonaws.com >> /etc/default/boto
 - echo [Boto] >> /etc/default/boto
 - ln -s /etc/default/boto /root/.boto
 - ln -s /etc/default/boto /home/pt-user/.boto
 - ln -s /etc/default/boto /etc/boto.cfg
 - pip install awscli
 - echo CREATE ROLE dalake PASSWORD \'HDP\' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN | su -c psql postgres
 - echo CREATE ROLE pgsql PASSWORD \'HDP\' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN | su -c psql postgres
 - echo "CREATE DATABASE fs OWNER dalake TEMPLATE = template0 ENCODING 'utf8'" | su -c psql postgres
 - echo "HDP" > /root/S3_BUCKET
 - |
    python -c "
    import boto
    bucket=open('/root/S3_BUCKET', 'r').readline().strip()
    boto.connect_s3().create_bucket(bucket)
    " 
{% if production %}
 -  AWS_CONFIG_FILE=/home/ubuntu/.boto aws s3 cp s3://HDP/db_dumps/{{hostname}}/{{hostname}}-latest-lake.pg_dump /tmp/
{% else %}
 -  AWS_CONFIG_FILE=/home/ubuntu/.boto aws --region us-west-2 s3 cp s3://HDP/db_dumps/{{hostname}}/{{hostname}}-latest-lake.pg_dump /tmp/
{% endif %}
 - su -c 'pg_restore -d fs /tmp/{{hostname}}-latest-lake.pg_dump' postgres
 - service apache2 restart
